USE [master]
GO

/****** Object:  Database [Jantrik.WaterQuest]    Script Date: 04/09/2015 19:01:39 ******/
CREATE DATABASE [Jantrik.WaterQuest] ON  PRIMARY 
( NAME = N'Jantrik.WaterQuest', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\Jantrik.WaterQuest.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Jantrik.WaterQuest_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\Jantrik.WaterQuest_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO
ALTER DATABASE [Jantrik.WaterQuest] SET COMPATIBILITY_LEVEL = 100
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Jantrik.WaterQuest].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [Jantrik.WaterQuest] SET ANSI_NULL_DEFAULT OFF
GO
ALTER DATABASE [Jantrik.WaterQuest] SET ANSI_NULLS OFF
GO
ALTER DATABASE [Jantrik.WaterQuest] SET ANSI_PADDING OFF
GO
ALTER DATABASE [Jantrik.WaterQuest] SET ANSI_WARNINGS OFF
GO
ALTER DATABASE [Jantrik.WaterQuest] SET ARITHABORT OFF
GO
ALTER DATABASE [Jantrik.WaterQuest] SET AUTO_CLOSE OFF
GO
ALTER DATABASE [Jantrik.WaterQuest] SET AUTO_CREATE_STATISTICS ON
GO
ALTER DATABASE [Jantrik.WaterQuest] SET AUTO_SHRINK OFF
GO
ALTER DATABASE [Jantrik.WaterQuest] SET AUTO_UPDATE_STATISTICS ON
GO
ALTER DATABASE [Jantrik.WaterQuest] SET CURSOR_CLOSE_ON_COMMIT OFF
GO
ALTER DATABASE [Jantrik.WaterQuest] SET CURSOR_DEFAULT  GLOBAL
GO
ALTER DATABASE [Jantrik.WaterQuest] SET CONCAT_NULL_YIELDS_NULL OFF
GO
ALTER DATABASE [Jantrik.WaterQuest] SET NUMERIC_ROUNDABORT OFF
GO
ALTER DATABASE [Jantrik.WaterQuest] SET QUOTED_IDENTIFIER OFF
GO
ALTER DATABASE [Jantrik.WaterQuest] SET RECURSIVE_TRIGGERS OFF
GO
ALTER DATABASE [Jantrik.WaterQuest] SET  DISABLE_BROKER
GO
ALTER DATABASE [Jantrik.WaterQuest] SET AUTO_UPDATE_STATISTICS_ASYNC OFF
GO
ALTER DATABASE [Jantrik.WaterQuest] SET DATE_CORRELATION_OPTIMIZATION OFF
GO
ALTER DATABASE [Jantrik.WaterQuest] SET TRUSTWORTHY OFF
GO
ALTER DATABASE [Jantrik.WaterQuest] SET ALLOW_SNAPSHOT_ISOLATION OFF
GO
ALTER DATABASE [Jantrik.WaterQuest] SET PARAMETERIZATION SIMPLE
GO
ALTER DATABASE [Jantrik.WaterQuest] SET READ_COMMITTED_SNAPSHOT OFF
GO
ALTER DATABASE [Jantrik.WaterQuest] SET HONOR_BROKER_PRIORITY OFF
GO
ALTER DATABASE [Jantrik.WaterQuest] SET  READ_WRITE
GO
ALTER DATABASE [Jantrik.WaterQuest] SET RECOVERY FULL
GO
ALTER DATABASE [Jantrik.WaterQuest] SET  MULTI_USER
GO
ALTER DATABASE [Jantrik.WaterQuest] SET PAGE_VERIFY CHECKSUM
GO
ALTER DATABASE [Jantrik.WaterQuest] SET DB_CHAINING OFF
GO
EXEC sys.sp_db_vardecimal_storage_format N'Jantrik.WaterQuest', N'ON'
GO